// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209141817_AddNozzleLabels")]
    partial class AddNozzleLabels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Backend.Models.DailyClosing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ClosingMeter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ClosingMeterB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("NozzleId")
                        .HasColumnType("int");

                    b.Property<decimal>("OpeningMeter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpeningMeterB")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NozzleId");

                    b.ToTable("DailyClosings");
                });

            modelBuilder.Entity("Backend.Models.Nozzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelSideA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelSideB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("Nozzles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FuelType = "Petrol",
                            LabelSideA = "Side A",
                            LabelSideB = "Side B",
                            MachineName = "Machine 1",
                            TankId = 1
                        },
                        new
                        {
                            Id = 2,
                            FuelType = "Diesel",
                            LabelSideA = "Side A",
                            LabelSideB = "Side B",
                            MachineName = "Machine 3",
                            TankId = 2
                        },
                        new
                        {
                            Id = 3,
                            FuelType = "Mobile Oil",
                            LabelSideA = "Side A",
                            LabelSideB = "Side B",
                            MachineName = "Rack/Shelf",
                            TankId = 3
                        },
                        new
                        {
                            Id = 4,
                            FuelType = "Hi-Octane",
                            LabelSideA = "Side A",
                            LabelSideB = "Side B",
                            MachineName = "Machine 2",
                            TankId = 4
                        });
                });

            modelBuilder.Entity("Backend.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Backend.Models.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Rates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentPrice = 280m,
                            FuelType = "Petrol",
                            LastUpdated = new DateTime(2026, 2, 9, 19, 18, 14, 219, DateTimeKind.Local).AddTicks(4472)
                        },
                        new
                        {
                            Id = 2,
                            CurrentPrice = 295m,
                            FuelType = "Diesel",
                            LastUpdated = new DateTime(2026, 2, 9, 19, 18, 14, 219, DateTimeKind.Local).AddTicks(4475)
                        },
                        new
                        {
                            Id = 3,
                            CurrentPrice = 600m,
                            FuelType = "Mobile Oil",
                            LastUpdated = new DateTime(2026, 2, 9, 19, 18, 14, 219, DateTimeKind.Local).AddTicks(4477)
                        },
                        new
                        {
                            Id = 4,
                            CurrentPrice = 330m,
                            FuelType = "Hi-Octane",
                            LastUpdated = new DateTime(2026, 2, 9, 19, 18, 14, 219, DateTimeKind.Local).AddTicks(4479)
                        });
                });

            modelBuilder.Entity("Backend.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCredit")
                        .HasColumnType("bit");

                    b.Property<int>("NozzleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RateAtSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("NozzleId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Backend.Models.StockRefill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPerLiter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("StockRefills");
                });

            modelBuilder.Entity("Backend.Models.Tank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Capacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20000m,
                            CurrentStock = 10000m,
                            FuelType = "Petrol",
                            TankName = ""
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 30000m,
                            CurrentStock = 15000m,
                            FuelType = "Diesel",
                            TankName = ""
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 1000m,
                            CurrentStock = 500m,
                            FuelType = "Mobile Oil",
                            TankName = ""
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 5000m,
                            CurrentStock = 2000m,
                            FuelType = "Hi-Octane",
                            TankName = ""
                        });
                });

            modelBuilder.Entity("Backend.Models.DailyClosing", b =>
                {
                    b.HasOne("Backend.Models.Nozzle", "Nozzle")
                        .WithMany()
                        .HasForeignKey("NozzleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nozzle");
                });

            modelBuilder.Entity("Backend.Models.Nozzle", b =>
                {
                    b.HasOne("Backend.Models.Tank", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("Backend.Models.Payment", b =>
                {
                    b.HasOne("Backend.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Backend.Models.Sale", b =>
                {
                    b.HasOne("Backend.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Backend.Models.Nozzle", "Nozzle")
                        .WithMany()
                        .HasForeignKey("NozzleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Nozzle");
                });

            modelBuilder.Entity("Backend.Models.StockRefill", b =>
                {
                    b.HasOne("Backend.Models.Tank", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("Backend.Models.Customer", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
